---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ebs-reader
  namespace: default
rules:
- apiGroups:
  - ebs.services.k8s.aws
  resources:
  verbs:
  - get
  - list
  - watch
